print('|=====================================================================|')
print('|                                                          Enero 2023 |')
print('|                                                         Itaugua, PY |')
print('|  Hola Mi Mismo,                                                     |')
print('|                                                                     |')
print('|      Te sientes entusiasmado por hacer estas cosas y vez quye no    |')
print('|      es muy díficil, incluso la sintaxis es más fácil.              |')
print('|      Deseo conocer Python a profundidad.                            |')
print('|      Termina pronto para empezar con Django.                        |')
print('|                                                                     |')
print('|                                              David Glez 🤠          |')
print('|                                                                     |')
print('|=====================================================================|')